# baseURL is empty for checking on localhost replace with http://innovativeeyecare.com.au/ when uploading to server
baseURL = ""
languageCode = "en-us"
title = "Hugo: Innovative Eye Care"
enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"
summaryLength = "30"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100

  [[menu.main]]
    identifier = "who-we-are"
    name = "Who We Are"
    url = "/who-we-are/"
    weight = -90

  [[menu.main]]
    identifier = "what-we-do"
    name = "What We Do"
    url = "/what-we-do/"
    weight = -80

  [[menu.main]]
    identifier = "patient-resources"
    name = "Patient Resources"
    url = "/patient-resources/"
    weight = -70

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -60

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = -50