# baseURL is empty for checking on localhost replace with http://innovativeeyecare.com.au/ when uploading to server
baseURL = ""
languageCode = "en-us"
title = "Hugo: Innovative Eye Care"
enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"