backend:
  name: git-gateway
  branch: staging
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true #
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Author URL",
          name: "author_url",
          widget: "string",
          required: false,
        }
      - {
          label: "Preview Image",
          name: "preview_image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "patient-resources"
    label: "Patient Resources"
    folder: "content/patient-resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          required: false,
        }
      - {
          label: "Preview Image",
          name: "preview_image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "who-we-are"
    label: "Who We Are"
    folder: "content/who-we-are"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Job Title",
          name: "jobtitle",
          widget: "string",
          required: false,
        }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Skill 1", name: "skill1", widget: "string", required: false }
      - {
          label: "Rating 1",
          name: "rating1",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - { label: "Skill 2", name: "skill2", widget: "string", required: false }
      - {
          label: "Rating 2",
          name: "rating2",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - { label: "Skill 3", name: "skill3", widget: "string", required: false }
      - {
          label: "Rating 3",
          name: "rating3",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - { label: "Skill 4", name: "skill4", widget: "string", required: false }
      - {
          label: "Rating 4",
          name: "rating4",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          valueType: "int",
          required: false,
        }
  - name: "what-we-do"
    label: "What We Do"
    folder: "content/what-we-do"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          required: false,
        }
      - {
          label: "Preview Image",
          name: "preview_image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
