backend:
  name: git-gateway
  branch: prod #local development (=staging)

# local development: when using the default proxy server port
# local_backend: true

media_folder: "static/uploads" # Media files stored in repo under images/uploads
public_folder: "/uploads" # Media files stored in repo under images/uploads

collections:
  - name: "author"
    label: "Who We Are"
    folder: "content/author"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Job Title",
          name: "jobtitle",
          widget: "string",
          required: false,
        }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Skill 1", name: "skill1", widget: "string", required: false }
      - {
          label: "Rating 1",
          name: "rating1",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - { label: "Skill 2", name: "skill2", widget: "string", required: false }
      - {
          label: "Rating 2",
          name: "rating2",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - { label: "Skill 3", name: "skill3", widget: "string", required: false }
      - {
          label: "Rating 3",
          name: "rating3",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - { label: "Skill 4", name: "skill4", widget: "string", required: false }
      - {
          label: "Rating 4",
          name: "rating4",
          widget: "number",
          valueType: "int",
          required: false,
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          valueType: "int",
          required: false,
        }
  - name: "what-we-do-cat"
    label: "What We Do Category"
    folder: "content/what-we-do-cat"
    create: true
    slug: "{{catno}}-{{slug}}"
    summary: "{{catno}} - {{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category No",
          name: "catno",
          widget: "string",
          pattern: ["^([A-Z]{2})([0-9]{2})$", "eg. SE01, SE02,.. SE10"],
        }
      - { label: "Image", name: "image", widget: "image" }
  - name: "what-we-do"
    label: "What We Do"
    folder: "content/what-we-do"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "what-we-do-cat",
          display_fields: ["catno", "title"],
          searchFields: ["title"],
          valueField: "catno",
        }
      - {
          label: "Preview Image",
          name: "preview_image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }