name: Run Unit tests
on:
  push:
jobs:
  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies 
        run: npm install
      - name: Prettier 
        run: prettier --check .
